services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: portal_actividades
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data    # Guarda los datos permanentemente, usar en un futuro

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:

# docker compose up --build  # para levantar el proyecto