"""Actualizacion de tabla actividades

Revision ID: 6e71ecbc6cb5
Revises: e24f8d0a2079
Create Date: 2026-09-01 11:19:32.309478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e71ecbc6cb5'
down_revision: Union[str, Sequence[str], None] = 'e24f8d0a2079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('tipo_actividad', sa.String(), nullable=True))
    op.add_column('actividades', sa.Column('prioridad', sa.String(), nullable=True))
    op.add_column('actividades', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    op.add_column('actividades', sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
    op.add_column('actividades', sa.Column('estimacion_min_hrs', sa.Float(), nullable=True))
    op.add_column('actividades', sa.Column('estimacion_max_hrs', sa.Float(), nullable=True))
    op.add_column('actividades', sa.Column('lider_tecnico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actividades', 'usuarios', ['lider_tecnico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actividades', type_='foreignkey')
    op.drop_column('actividades', 'lider_tecnico_id')
    op.drop_column('actividades', 'estimacion_max_hrs')
    op.drop_column('actividades', 'estimacion_min_hrs')
    op.drop_column('actividades', 'fecha_vencimiento')
    op.drop_column('actividades', 'fecha_inicio')
    op.drop_column('actividades', 'prioridad')
    op.drop_column('actividades', 'tipo_actividad')
    # ### end Alembic commands ###
