"""crear tablas iniciales

Revision ID: 7edd8848e4d7
Revises: 
Create Date: 2026-08-25 10:33:50.700670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edd8848e4d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('horas_estimadas', sa.Float(), nullable=True),
    sa.Column('equipo', sa.String(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
