"""agregar columna name_ users opcional en db

Revision ID: 7f81e7194523
Revises: ba0ccf253186
Create Date: 2026-08-26 11:14:23.224424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f81e7194523'
down_revision: Union[str, Sequence[str], None] = 'ba0ccf253186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('name_users', sa.String(), nullable=True))
    op.drop_column('usuarios', 'users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('users', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'name_users')
    # ### end Alembic commands ###
