"""crear tabla de areas y relacionar con actividades

Revision ID: a3d60b9fe42b
Revises: 7f81e7194523
Create Date: 2026-08-26 11:34:34.201403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d60b9fe42b'
down_revision: Union[str, Sequence[str], None] = '7f81e7194523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    op.add_column('actividades', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actividades', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actividades', type_='foreignkey')
    op.drop_column('actividades', 'area_id')
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
