"""agregar columna users opcional en db

Revision ID: ba0ccf253186
Revises: 7edd8848e4d7
Create Date: 2026-08-26 11:10:13.899311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0ccf253186'
down_revision: Union[str, Sequence[str], None] = '7edd8848e4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividades', 'equipo')
    op.drop_column('actividades', 'horas_estimadas')
    op.add_column('usuarios', sa.Column('users', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'users')
    op.add_column('actividades', sa.Column('horas_estimadas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('actividades', sa.Column('equipo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
