"""Cambio en tabla de areas

Revision ID: c974a418b1f3
Revises: a3d60b9fe42b
Create Date: 2026-08-28 12:18:32.467128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c974a418b1f3'
down_revision: Union[str, Sequence[str], None] = 'a3d60b9fe42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
