"""Relacion de id con usuarios

Revision ID: e24f8d0a2079
Revises: c974a418b1f3
Create Date: 2026-08-28 12:47:41.381527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24f8d0a2079'
down_revision: Union[str, Sequence[str], None] = 'c974a418b1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'area_id')
    # ### end Alembic commands ###
